server:
  port:8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studentCrud?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false